/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.vistas;

import com.unab.edu.DAO.ClsEscala;
import com.unab.edu.DAO.ClsVuelo;
import com.unab.edu.DAO.InnerJoinVuelo;
import com.unab.edu.Entidades.Escala;
import com.unab.edu.Entidades.Vuelo;
import com.unab.edu.sistemaaeropuerto.CambioPanel;
import com.unab.edu.sistemaaeropuerto.frmMenuUser;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class PnlListaVuelos extends javax.swing.JPanel {

    /**
     * Creates new form PnlListaVuelos
     */
    public PnlListaVuelos() {
        initComponents();
        CargarTablaVuelos();
    }
    public frmMenuUser menuUser;
    CambioPanel CmPanel = new CambioPanel();

    void CargarTablaVuelos() {
        ClsEscala clsEscala = new ClsEscala();
        String Titulos[] = {"Vuelo", "N Escala", "AeropuertoDestino", "Precio", "Tipo de Vuelo", "Fecha", "Hora", "Descuento", "Fecha Max Descuento"};
        DefaultTableModel ModeloT = new DefaultTableModel(null, Titulos);
        ClsVuelo clsVuelos = new ClsVuelo();
        ArrayList<InnerJoinVuelo> Vuelos = clsVuelos.MostrarVuelosOrigen(1);
        String filas[] = new String[10];
        Vuelo vuelo = new Vuelo();

        for (var IterarVuelo : Vuelos) {
            vuelo = clsVuelos.SeleccionarVuelo(IterarVuelo.getVuelo());
            ArrayList<Escala> Escalas = clsEscala.MostrarEscala(vuelo.getIdIterinario());
            if (Escalas.size() >= 1) {
                for (var IterarEscala : Escalas) {
                    filas[0] = String.valueOf(IterarVuelo.getVuelo());
                    filas[1] = String.valueOf(IterarEscala.getNumeroEscala());
                    filas[2] = IterarEscala.getNombre();
                    filas[3] = String.valueOf(IterarEscala.getPrecio());
                    filas[4] = IterarVuelo.getTipo();
                    filas[5] = String.valueOf(IterarVuelo.getFecha());
                    filas[6] = IterarVuelo.getHora() + ":" + IterarVuelo.getMinutos();
                    filas[7] = String.valueOf(IterarVuelo.getDescuento()) + "%";
                    if (IterarVuelo.getFechaDesc() == null) {
                        filas[8] = "";
                    } else {
                        filas[8] = String.valueOf(IterarVuelo.getFechaDesc());
                    }
                    ModeloT.addRow(filas);
                }
            }

        }
        tbVuelos.setModel(ModeloT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbVuelos = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));

        tbVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbVuelos);

        btnNuevo.setText("Nuevo Pasaje");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnNuevo)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnNuevo)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        int fila = tbVuelos.getSelectedRow();
        String idVuelo = String.valueOf(tbVuelos.getValueAt(fila, 0));
        String NEscala = String.valueOf(tbVuelos.getValueAt(fila, 1));
        String Precio = String.valueOf(tbVuelos.getValueAt(fila, 3));
        String Descuento = String.valueOf(tbVuelos.getValueAt(fila, 7));
        double PrecioVuelo = Double.parseDouble(Precio);
        String[] c = Descuento.split("%");
        double PorcentajeDescuento = Double.parseDouble(c[0]);
        PrecioVuelo = PrecioVuelo - (PrecioVuelo * (PorcentajeDescuento / 100));
        ClsVuelo clsVuelo = new ClsVuelo();
        Vuelo vuelo = new Vuelo();
        int NVuelo = Integer.parseInt(idVuelo);
        vuelo = clsVuelo.SeleccionarVuelo(NVuelo);
        JOptionPane.showMessageDialog(null, NVuelo);

        PnlPasaje frmPasaje = new PnlPasaje();
        CmPanel.ModificarPanel(menuUser.PnlContenedor, frmPasaje);
        frmPasaje.txtVuelo.setText(idVuelo);
        frmPasaje.txtNEscala.setText(NEscala);
        frmPasaje.txtPrecio.setText(String.valueOf(PrecioVuelo));
        frmPasaje.idAvion = vuelo.getIdAvion();
        frmPasaje.DisplayMemberClase();

    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbVuelos;
    // End of variables declaration//GEN-END:variables
}
