/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.vistas;

import com.unab.edu.DAO.ClsClase;
import com.unab.edu.DAO.ClsEscala;
import com.unab.edu.DAO.ClsPasaje;
import com.unab.edu.DAO.ClsPasajero;
import com.unab.edu.DAO.ClsVuelo;
import com.unab.edu.Entidades.Clases;
import com.unab.edu.Entidades.Pasaje;
import com.unab.edu.Entidades.Vuelo;
import com.unab.edu.sistemaaeropuerto.frmMenuUsuario;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PREDATOR
 */
public class PnlPasaje extends javax.swing.JPanel {

    /**
     * Creates new form PnlPasaje
     */
    public PnlPasaje() {
        initComponents();
    }

    public int NVuelo;
    String valueMemberPasajero;
    String valueMemberClase[];
    int contadorPasajero = 1;
    int contadorClase;
    ClsVuelo clsvuelo = new ClsVuelo();
    Vuelo vuelo = new Vuelo();
    int idClase;
    public frmMenuUsuario menuUser;
    public double Precio;

    void DisplayMemberClase() {
        ClsVuelo clsVuelo = new ClsVuelo();
        Vuelo vuelo = new Vuelo();
        vuelo = clsVuelo.SeleccionarVuelo(NVuelo);

        DefaultComboBoxModel cbdefaDefault = new DefaultComboBoxModel();
        ClsClase clase = new ClsClase();
        ArrayList<Clases> clases = clase.MostrarClase(vuelo.getIdAvion());
        valueMemberClase = new String[clases.size() + 1];
        String filas[] = new String[4];
        contadorClase = 1;
        cbdefaDefault.addElement("");
        for (var IterarDatosClase : clases) {
            filas[0] = String.valueOf(IterarDatosClase.getIdClase());
            filas[1] = String.valueOf(IterarDatosClase.getNombreClase());
            valueMemberClase[contadorClase] = filas[0];
            cbdefaDefault.addElement(filas[1]);
            contadorClase++;
        }
        cbClase.setModel(cbdefaDefault);
    }

    void DisplayAsientos() {
        ClsPasaje clsPasaje = new ClsPasaje();
        ClsVuelo clsVuelo = new ClsVuelo();
        Vuelo vuelo = new Vuelo();
        vuelo = clsVuelo.SeleccionarVuelo(NVuelo);
        DefaultComboBoxModel cbdefaDefault = new DefaultComboBoxModel();
        ClsClase clsclase = new ClsClase();
        ArrayList<Clases> clases = clsclase.MostrarClase(vuelo.getIdAvion());
        cbdefaDefault.removeAllElements();
        cbdefaDefault.addElement("");
        Clases clase = new Clases();
        int Asiento = 0;
        ArrayList<Pasaje> AsientosOcupados = clsPasaje.MostrarPasajes(NVuelo, idClase);
        for (var iterarclases : clases) {
            if (iterarclases.getIdClase() == idClase) {
                clase.setNAsientos(iterarclases.getNAsientos());
                break;
            } else {
                Asiento = Asiento + iterarclases.getNAsientos();
            }
        }
        for (int i = 0; i < clase.getNAsientos(); i++) {

            Asiento = Asiento + 1;
            String add = String.valueOf(Asiento);
            boolean ComprobarAsiento = false;
            for (var iterarAsientos : AsientosOcupados) {
                if (iterarAsientos.getNAsiento() == Asiento) {
                    ComprobarAsiento = true;
                    break;
                }
            }
            if (ComprobarAsiento == false) {
                cbdefaDefault.addElement(add);
            }

        }
        cbAsientos.setModel(cbdefaDefault);
    }
    ClsEscala clsEscala = new ClsEscala();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtpPasaje = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVuelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbClase = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        bttnGuardar = new javax.swing.JButton();
        txtxPasajero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNEscala = new javax.swing.JTextField();
        cbAsientos = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jtpPasaje.setBackground(new java.awt.Color(51, 102, 255));
        jtpPasaje.setForeground(new java.awt.Color(255, 255, 255));
        jtpPasaje.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pasaje");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DUI:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vuelo:");

        txtVuelo.setBackground(new java.awt.Color(0, 0, 0));
        txtVuelo.setForeground(new java.awt.Color(255, 255, 255));
        txtVuelo.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Clase:");

        cbClase.setBackground(new java.awt.Color(0, 0, 0));
        cbClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbClase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClaseItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Asiento:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio:");

        txtPrecio.setBackground(new java.awt.Color(0, 0, 0));
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setEnabled(false);

        bttnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        bttnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        bttnGuardar.setText("Guardar");
        bttnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnGuardarActionPerformed(evt);
            }
        });

        txtxPasajero.setBackground(new java.awt.Color(0, 0, 0));
        txtxPasajero.setForeground(new java.awt.Color(255, 255, 255));
        txtxPasajero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtxPasajeroFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("N Escala:");

        txtNEscala.setBackground(new java.awt.Color(0, 0, 0));
        txtNEscala.setForeground(new java.awt.Color(255, 255, 255));
        txtNEscala.setEnabled(false);

        cbAsientos.setBackground(new java.awt.Color(0, 0, 0));
        cbAsientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtVuelo)
                        .addComponent(cbClase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrecio)
                        .addComponent(txtxPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(39, 39, 39)
                            .addComponent(txtNEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bttnGuardar)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(187, 187, 187)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtxPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(bttnGuardar)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jtpPasaje.addTab("Registro Pasaje", jPanel2);

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jtpPasaje.addTab("Lista Pasajes", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jtpPasaje, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jtpPasaje, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnGuardarActionPerformed
        ClsPasaje pasajes = new ClsPasaje();
        ClsPasajero clsPasajero = new ClsPasajero();
        Pasaje pasaje = new Pasaje();
        pasaje.setIdPasajero((clsPasajero.IdPasajero(txtxPasajero.getText())));
        pasaje.setIdVuelo(Integer.parseInt(txtVuelo.getText()));
        pasaje.setIdClase(Integer.parseInt(valueMemberClase[cbClase.getSelectedIndex()]));
        pasaje.setNAsiento(Integer.parseInt(String.valueOf(cbAsientos.getSelectedItem())));
        pasaje.setPrecionTotal(Float.parseFloat(txtPrecio.getText()));
        String usuario = menuUser.Usuario;
        pasaje.setNombreUsuario(usuario);
        pasaje.setNEscala(Integer.parseInt(txtNEscala.getText()));
        pasajes.AgregarPasaje(pasaje);
        
    }//GEN-LAST:event_bttnGuardarActionPerformed

    private void txtxPasajeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtxPasajeroFocusLost
        String Documento = txtxPasajero.getText();
        ClsPasajero clsPasajero = new ClsPasajero();
        if (clsPasajero.ExistenciaPasajero(Documento) == false) {
            int resp = JOptionPane.showConfirmDialog(null, "Pasajero no encontrado, ¿Desea Registrar Pasajero?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (resp == 0) {
                menuUser.btnPasajeros.doClick();
            } else {
                txtxPasajero.setText("");
            }
        }
    }//GEN-LAST:event_txtxPasajeroFocusLost

    private void cbClaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClaseItemStateChanged
        idClase = (Integer.parseInt(valueMemberClase[cbClase.getSelectedIndex()]));
        DisplayAsientos();
        ClsClase clsClase = new ClsClase();
        Clases clase = new Clases();
        clase = clsClase.SeleccionarClas(idClase);
        double PrecioClase = Precio;
        double PorcentajeExtra = (clase.getPorcentajeEPrecio());
        PrecioClase = PrecioClase + (PrecioClase * (PorcentajeExtra / 100.0));
        if (Integer.parseInt(valueMemberClase[cbClase.getSelectedIndex()]) > 0) {
            txtPrecio.setText(String.valueOf(PrecioClase));
        }
    }//GEN-LAST:event_cbClaseItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnGuardar;
    private javax.swing.JComboBox<String> cbAsientos;
    private javax.swing.JComboBox<String> cbClase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jtpPasaje;
    public javax.swing.JTextField txtNEscala;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtVuelo;
    private javax.swing.JTextField txtxPasajero;
    // End of variables declaration//GEN-END:variables

}
