/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.vistas;

import com.unab.edu.DAO.ClsClase;
import com.unab.edu.DAO.ClsEscala;
import com.unab.edu.DAO.ClsPasaje;
import com.unab.edu.DAO.ClsPasajero;
import com.unab.edu.DAO.ClsVuelo;
import com.unab.edu.DAO.InnerJoinVuelo;
import com.unab.edu.Entidades.Clases;
import com.unab.edu.Entidades.Escala;
import com.unab.edu.Entidades.Pasaje;
import com.unab.edu.Entidades.Pasajero;
import com.unab.edu.Entidades.Vuelo;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PREDATOR
 */
public class PnlPasaje extends javax.swing.JPanel {

    /**
     * Creates new form PnlPasaje
     */
    public PnlPasaje() {
        initComponents();
        CargarTabla();
    }

    public int idAvion;
    String valueMemberPasajero;
    String valueMemberClase[];
    int contadorPasajero = 1;
    int contadorClase;
    ClsVuelo clsvuelo = new ClsVuelo();
    Vuelo vuelo = new Vuelo();

    void DisplayMemberClase() {
        JOptionPane.showMessageDialog(null, idAvion);
        DefaultComboBoxModel cbdefaDefault = new DefaultComboBoxModel();
        ClsClase clase = new ClsClase();
        ArrayList<Clases> claseses = clase.MostrarClase(idAvion);
        valueMemberClase = new String[claseses.size() + 1];
        String filas[] = new String[4];
        contadorClase = 1;
        cbdefaDefault.addElement("");
        for (var IterarDatosClase : claseses) {
                filas[0] = String.valueOf(IterarDatosClase.getIdAvion());
                filas[1] = String.valueOf(IterarDatosClase.getNombreClase());
                valueMemberClase[contadorClase] = filas[0];
                cbdefaDefault.addElement(filas[1]);
                contadorClase++;
        }
        cbClase.setModel(cbdefaDefault);
    }

    ClsEscala clsEscala = new ClsEscala();

    void CargarTabla() {
        String Titulos[] = {"idPasaje", "idPasajero", "idVuelo", "idClase", "NAsiento", "precioTotal"};
        DefaultTableModel ModeloT = new DefaultTableModel(null, Titulos);
        ClsPasaje clasePasaje = new ClsPasaje();
        ArrayList<Pasaje> pasajes = clasePasaje.MostrarPasajes();
        String filas[] = new String[7];
        for (var Iterar : pasajes) {
            filas[0] = String.valueOf(Iterar.getIdPasaje());
            filas[1] = String.valueOf(Iterar.getIdPasajero());
            filas[2] = String.valueOf(Iterar.getIdVuelo());
            filas[3] = String.valueOf(Iterar.getIdClase());
            filas[4] = String.valueOf(Iterar.getNAsiento());
            filas[5] = String.valueOf(Iterar.getPrecionTotal());
            ModeloT.addRow(filas);
        }
        tbPasajes.setModel(ModeloT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtpPasaje = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVuelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbClase = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtAsiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        bttnGuardar = new javax.swing.JButton();
        txtxPasajero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNEscala = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPasajes = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jtpPasaje.setBackground(new java.awt.Color(51, 102, 255));
        jtpPasaje.setForeground(new java.awt.Color(255, 255, 255));
        jtpPasaje.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pasaje");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DUI:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vuelo:");

        txtVuelo.setBackground(new java.awt.Color(0, 0, 0));
        txtVuelo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Clase:");

        cbClase.setBackground(new java.awt.Color(0, 0, 0));
        cbClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Asiento:");

        txtAsiento.setBackground(new java.awt.Color(0, 0, 0));
        txtAsiento.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio:");

        txtPrecio.setBackground(new java.awt.Color(0, 0, 0));
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));

        bttnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        bttnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        bttnGuardar.setText("Guardar");
        bttnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnGuardarActionPerformed(evt);
            }
        });

        txtxPasajero.setBackground(new java.awt.Color(0, 0, 0));
        txtxPasajero.setForeground(new java.awt.Color(255, 255, 255));
        txtxPasajero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtxPasajeroFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("N Escala:");

        txtNEscala.setBackground(new java.awt.Color(0, 0, 0));
        txtNEscala.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtVuelo)
                        .addComponent(cbClase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAsiento)
                        .addComponent(txtPrecio)
                        .addComponent(txtxPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(39, 39, 39)
                            .addComponent(txtNEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(205, 205, 205))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnGuardar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtxPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(bttnGuardar)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jtpPasaje.addTab("Registro Pasaje", jPanel2);

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        tbPasajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPasajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPasajesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPasajes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jtpPasaje.addTab("Lista Pasajes", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jtpPasaje, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jtpPasaje, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnGuardarActionPerformed
        ClsPasaje pasajes = new ClsPasaje();
        Pasaje pasaje = new Pasaje();
        pasaje.setIdVuelo(Integer.parseInt(txtVuelo.getText()));
        pasaje.setIdClase(Integer.parseInt(valueMemberClase[cbClase.getSelectedIndex()]));
        pasaje.setNAsiento(Integer.parseInt(txtAsiento.getText()));
        pasaje.setPrecionTotal(Float.parseFloat(txtPrecio.getText()));
        pasajes.AgregarPasaje(pasaje);
        CargarTabla();
    }//GEN-LAST:event_bttnGuardarActionPerformed

    private void tbPasajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPasajesMouseClicked
        jtpPasaje.setSelectedIndex(jtpPasaje.indexOfComponent(jPanel2));
        int fila = tbPasajes.getSelectedRow();

        String idPasaje = String.valueOf(tbPasajes.getValueAt(fila, 0));
        String idVuelo = String.valueOf(tbPasajes.getValueAt(fila, 2));
        String idClase = String.valueOf(tbPasajes.getValueAt(fila, 3));
        String NAsiento = String.valueOf(tbPasajes.getValueAt(fila, 4));
        String precioTotal = String.valueOf(tbPasajes.getValueAt(fila, 5));

        txtVuelo.setText(idVuelo);
        txtAsiento.setText(NAsiento);
        txtPrecio.setText(precioTotal);
        int seleccionadordevista2 = 0;
        for (var iterar : valueMemberClase) {
            if (idClase.equals(iterar)) {
                cbClase.setSelectedIndex(seleccionadordevista2);
            }
            seleccionadordevista2 += 1;
        }

    }//GEN-LAST:event_tbPasajesMouseClicked

    private void txtxPasajeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtxPasajeroFocusLost
        String Documento = txtxPasajero.getText();
        ClsPasajero clsPasajero = new ClsPasajero();
        if (clsPasajero.ExistenciaPasajero(Documento) == false) {
            int resp = JOptionPane.showConfirmDialog(null, "Pasajero no encontrado, ¿Desea Registrar Pasajero?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if (resp == 0) {
                
            } else {
                txtxPasajero.setText("");
            }
        }
    }//GEN-LAST:event_txtxPasajeroFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnGuardar;
    private javax.swing.JComboBox<String> cbClase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jtpPasaje;
    private javax.swing.JTable tbPasajes;
    private javax.swing.JTextField txtAsiento;
    public javax.swing.JTextField txtNEscala;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtVuelo;
    private javax.swing.JTextField txtxPasajero;
    // End of variables declaration//GEN-END:variables
}
