/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.OperacionesBd;

import com.unab.edu.DAO.ClsAvion;
import com.unab.edu.Entidades.Avion;
import com.unab.edu.sistemaaeropuerto.CambioPanel;
import com.unab.edu.sistemaaeropuerto.frmMenuAdmin;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class PnlAvion extends javax.swing.JPanel {

    /**
     * Creates new form PnlAvion
     */
    public PnlAvion() {
        initComponents();
        CargarTabla();
    }
    
    PnlClases frmClase = new PnlClases();
    public frmMenuAdmin menuAdmin;
    CambioPanel cambio = new CambioPanel();
    
    void LimpiarCajasdeTexto(){
        txtId.setText("");
        txtCapacidad.setText("");
        txtModelo.setText("");
    }
    
    void CargarTabla() {
        String Titulos[] = {"ID", "Modelo", "Capacidad"};
        DefaultTableModel ModeloT = new DefaultTableModel(null, Titulos);
        ClsAvion clsAvion = new ClsAvion();
        ArrayList<Avion> Companies = clsAvion.MostrarAvion();
        String filas[] = new String[4];
        for (var IterarCom : Companies) {
            filas[0] = String.valueOf(IterarCom.getIdAvion());
            filas[1] = String.valueOf(IterarCom.getModeloAvion());
            filas[2] = String.valueOf(IterarCom.getCapacidad());
            ModeloT.addRow(filas);
        }
        tbAviones.setModel(ModeloT);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbPAvion = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnClase = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAviones = new javax.swing.JTable();

        setBackground(new java.awt.Color(51, 102, 255));

        tbPAvion.setBackground(new java.awt.Color(51, 102, 255));
        tbPAvion.setForeground(new java.awt.Color(255, 255, 255));
        tbPAvion.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aviones");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modelo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Capacidad:");

        txtCapacidad.setBackground(new java.awt.Color(0, 0, 0));
        txtCapacidad.setForeground(new java.awt.Color(255, 255, 255));

        txtModelo.setBackground(new java.awt.Color(0, 0, 0));
        txtModelo.setForeground(new java.awt.Color(255, 255, 255));

        txtId.setBackground(new java.awt.Color(0, 0, 0));
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setEnabled(false);

        btnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnClase.setBackground(new java.awt.Color(0, 0, 0));
        btnClase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClase.setForeground(new java.awt.Color(255, 255, 255));
        btnClase.setText("Ver Clases");
        btnClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnGuardar)
                .addGap(111, 111, 111)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(117, 117, 117)
                .addComponent(btnClase)
                .addGap(100, 100, 100))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                            .addComponent(txtModelo)
                            .addComponent(txtCapacidad)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)))
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar)
                    .addComponent(btnClase))
                .addGap(195, 195, 195))
        );

        tbPAvion.addTab("Registro Aviones", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        tbAviones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAviones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAvionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAviones);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        tbPAvion.addTab("Lista Aviones", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbPAvion, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbPAvion, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       if(txtModelo.getText().isEmpty() == true || txtCapacidad.getText().isEmpty() == true){
            JOptionPane.showMessageDialog(null, "Rellene todos los campos necesarios");
       }else{
       ClsAvion avion = new ClsAvion();
        Avion aviones = new Avion();
        aviones.setModeloAvion(txtModelo.getText());
        aviones.setCapacidad(Integer.parseInt(txtCapacidad.getText()));
        avion.AgregarAvion(aviones);
        LimpiarCajasdeTexto();
        CargarTabla();
       }
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(txtId.getText().isEmpty() == true){
            JOptionPane.showMessageDialog(null, "Rellene todos los campos necesarios");
       }else{
        ClsAvion avion = new ClsAvion();
        Avion aviones = new Avion();
        aviones.setIdAvion(Integer.parseInt(txtId.getText()));
        avion.BorrarAvion(aviones);
        LimpiarCajasdeTexto();
        CargarTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
         if(txtId.getText().isEmpty() == true || txtModelo.getText().isEmpty() == true || txtCapacidad.getText().isEmpty() == true){
            JOptionPane.showMessageDialog(null, "Rellene todos los campos necesarios");
       }else{
        ClsAvion avion = new ClsAvion();
        Avion aviones = new Avion();
        aviones.setIdAvion(Integer.parseInt(txtId.getText()));
        aviones.setModeloAvion(txtModelo.getText());
        aviones.setCapacidad(Integer.parseInt(txtCapacidad.getText()));
        avion.ActualizarAvion(aviones);
        LimpiarCajasdeTexto();
        CargarTabla();
         }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tbAvionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAvionesMouseClicked
        tbPAvion.setSelectedIndex(tbPAvion.indexOfComponent(jPanel2));
        int fila = tbAviones.getSelectedRow();

        String ID = String.valueOf(tbAviones.getValueAt(fila, 0));
        String Modelo = String.valueOf(tbAviones.getValueAt(fila, 1));
        String Capacidad = String.valueOf(tbAviones.getValueAt(fila, 2));
        txtId.setText(ID);
        txtModelo.setText(Modelo);
        txtCapacidad.setText(Capacidad);
    }//GEN-LAST:event_tbAvionesMouseClicked

    private void btnClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaseActionPerformed
      if(txtId.getText().isEmpty() == true){
            JOptionPane.showMessageDialog(null, "Seleccione un Avion para ver su Clase");
             tbPAvion.setSelectedIndex(tbPAvion.indexOfComponent(jPanel3));
        int fila = tbAviones.getSelectedRow();
       }else{
       cambio.ModificarPanel(menuAdmin.PnlContenedor, frmClase);
       int idAvion = Integer.parseInt(txtId.getText());
       frmClase.idAvion = idAvion;
       frmClase.CargarTabla();
      }
    }//GEN-LAST:event_btnClaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnClase;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAviones;
    private javax.swing.JTabbedPane tbPAvion;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
