/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.sistemaaeropuerto;

import com.unab.edu.vistas.PnlAeropuerto;
import com.unab.edu.vistas.PnlAvion;
import com.unab.edu.vistas.PnlClases;
import com.unab.edu.vistas.PnlCompania;
import com.unab.edu.vistas.PnlEscala;
import com.unab.edu.vistas.PnlPasajero;
import com.unab.edu.vistas.PnlTiposdeVuelo;
import com.unab.edu.vistas.PnlVuelos;

/**
 *
 * @author Usuario
 */
public class frmMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuAdmin
     */
    public frmMenuAdmin() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }
    
    public frmMenuAdmin menuAdmin;

    CambioPanel CmPanel = new CambioPanel();
    PnlAeropuerto frmAeropuerto = new PnlAeropuerto();
    PnlCompania frmCompania = new PnlCompania();
    PnlAvion frmAvion = new PnlAvion();
    PnlVuelos frmVuelo = new PnlVuelos();
    PnlTiposdeVuelo frmTipos = new PnlTiposdeVuelo();
    PnlEscala frmEscala = new PnlEscala();
    PnlClases frmClase = new PnlClases();
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        btnCompany = new javax.swing.JButton();
        btnAeropuerto = new javax.swing.JButton();
        btnAvion = new javax.swing.JButton();
        btnVuelo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTipos = new javax.swing.JButton();
        PnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN");
        setBackground(new java.awt.Color(102, 255, 255));

        panel1.setBackground(new java.awt.Color(51, 102, 255));

        btnCompany.setBackground(new java.awt.Color(51, 102, 255));
        btnCompany.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCompany.setLabel("Compañia");
        btnCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompanyActionPerformed(evt);
            }
        });

        btnAeropuerto.setBackground(new java.awt.Color(51, 102, 255));
        btnAeropuerto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAeropuerto.setText("Aeropuerto");
        btnAeropuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAeropuertoActionPerformed(evt);
            }
        });

        btnAvion.setBackground(new java.awt.Color(51, 102, 255));
        btnAvion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAvion.setText("Avion");
        btnAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvionActionPerformed(evt);
            }
        });

        btnVuelo.setBackground(new java.awt.Color(51, 102, 255));
        btnVuelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVuelo.setText("Vuelos");
        btnVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVueloActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flight_30822 - Copy.png"))); // NOI18N

        btnTipos.setBackground(new java.awt.Color(51, 102, 255));
        btnTipos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTipos.setText("Tipos de Vuelos");
        btnTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAeropuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
            .addComponent(btnCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(401, Short.MAX_VALUE))
        );

        PnlContenedor.setBackground(new java.awt.Color(0, 153, 204));
        PnlContenedor.setLayout(new javax.swing.BoxLayout(PnlContenedor, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompanyActionPerformed
        CmPanel.ModificarPanel(PnlContenedor, frmCompania);
    }//GEN-LAST:event_btnCompanyActionPerformed

    private void btnAeropuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAeropuertoActionPerformed
        CmPanel.ModificarPanel(PnlContenedor, frmAeropuerto);
    }//GEN-LAST:event_btnAeropuertoActionPerformed

    private void btnAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvionActionPerformed
        CmPanel.ModificarPanel(PnlContenedor, frmAvion);
        frmAvion.menuAdmin = this.menuAdmin;
    }//GEN-LAST:event_btnAvionActionPerformed

    private void btnVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVueloActionPerformed
        CmPanel.ModificarPanel(PnlContenedor, frmVuelo);
        frmVuelo.menuAdmin = this.menuAdmin;
    }//GEN-LAST:event_btnVueloActionPerformed

    private void btnTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiposActionPerformed
        CmPanel.ModificarPanel(PnlContenedor, frmTipos);
    }//GEN-LAST:event_btnTiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PnlContenedor;
    private javax.swing.JButton btnAeropuerto;
    private javax.swing.JButton btnAvion;
    private javax.swing.JButton btnCompany;
    private javax.swing.JButton btnTipos;
    private javax.swing.JButton btnVuelo;
    private javax.swing.JLabel jLabel1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
